# https://www.elastic.co/guide/en/kibana/reference/current/docker.html
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana
  namespace: elk
spec:
  selector:
    matchLabels:
      app: kibana
  serviceName: "kibana"
  replicas: 1
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: kibana
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu:    1.0
          requests:
            cpu:    0.1
        volumeMounts:
        - name: config
          mountPath: /tmp/volumes/kibana/config/kibana.yml
          subPath: kibana.yml
      volumes:
      - name: config
        configMap:
          name: kibana-config
