# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elk
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: "elasticsearch"
  replicas: 1
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: elasticsearch
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        # https://github.com/elastic/elasticsearch-docker/issues/32
        command: ['sh', '-c', 'chown -R 1000:1000 /tmp/volumes/elasticsearch/data && sysctl -w vm.max_map_count=262144']
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /tmp/volumes/elasticsearch/data
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        imagePullPolicy: Always
        env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: cluster.initial_master_nodes
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ES_JAVA_OPTS
            value: "-Xms4g -Xmx4g"
        resources:
          requests:
            cpu: 3
            memory: 6Gi
          limits:
            cpu: 3
            memory: 6Gi
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /tmp/volumes/elasticsearch/data
        - name: config
          mountPath: /tmp/volumes/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: config
        configMap:
          name: elasticsearch-config
      # - name: data
      #   emptyDir: {}\
      nodeSelector:
        role: es-master
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 250Gi
